import { defineConfig } from "vite";
import path from "path";
import vue from "@vitejs/plugin-vue";
import { fileURLToPath } from "url";
import dts from 'vite-plugin-dts'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(), 
    dts({ rollupTypes: true })
  ],
  
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'active-designsystem',
      formats: ['es'], // adding 'umd' requires globals set to every external module
      fileName:`active-designsystem`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue', /primevue\/.+/], // not every external has a global
      output: {
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});